name: creapp
services:
  creappapi:
    container_name: creappapi
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - /root/backup/creapp/api-data:/app/uploads
    ports:
      - "5002:5000"
    depends_on:
      - postgres
    networks:
      - caddy-net
  
  postgres:
    container_name: creapp_postgres
    image: postgres:16
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - /root/backup/creapp/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - caddy-net

  redis:
    container_name: creapp_redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - /root/backup/creapp/redis-data:/data
    ports:
      - "6379:6379" # optional, remove in prod if not needed
    networks:
      - caddy-net

networks:
  caddy-net:
    driver: bridge
    external: true